### ISSUE TITLE
Invoice set to cancelled if paid via another method

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/woocommerce-plugin#2] opened 2018-02-02 18:49 UTC
Scenario: 

Customer tries to use BTCPay, but for some reason goes back to the order and then wants to pay with another payment. Pays via CC or some other method and order is completed. 

BTCPay 15 minute timer expires and sets order to cancelled, even though previously set to paid by other payment method.

**Comment by NicolasDorier** [comment] 2018-02-04 13:33
The problem is coming from a race condition happening which generate 2 BTCPay invoices if the user double click. https://github.com/btcpayserver/woocommerce-plugin/blob/master/src/class-wc-gateway-bitpay.php#L570

Original bitpay plugin do not have this problem because no notification is sent during expiration.
I must fix the race condition.

**Comment by NicolasDorier** [comment] 2018-02-04 14:48
Actually what you report to me this is not a bug, I don't know how to fix that correctly. On woocommerce site I have no way to know if another payment method was chosen.

**Comment by NicolasDorier** [comment] 2018-02-04 15:30
I created https://github.com/btcpayserver/woocommerce-plugin/releases/tag/v2.2.17 so at least you can decide to ignore an event.

**Comment by NicolasDorier** [comment] 2018-02-04 22:21
fixed on https://github.com/btcpayserver/woocommerce-plugin/releases/tag/v2.2.18

**Closed by NicolasDorier** 2018-02-04 22:21 UTC
